// Nós (Eduardo Rost, Fabiano Menegussi, Renan Santos), garantimos que:
//
// - Não utilizamos código fonte obtidos de outros estudantes,
// ou fonte não autorizada, seja modificado ou cópia literal.
// - Todo código usado em nosso trabalho ´e resultado do nosso
// trabalho original, ou foi derivado de um
// código publicado nos livros texto desta disciplina.
// - Temos total ciência das consequências em caso de violarmos estes termos.
package estruturasdados.trabalhoGB;

import br.unisinos.imagepanel.ImagePanel;
import estruturasdados.trabalhoGB.Domain.QuadTree;
import java.awt.Color;
import java.awt.Component;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JSlider;
import javax.swing.filechooser.FileFilter;

public class Index extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
        invalidFile = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        compressionRateSlider = new javax.swing.JSlider();
        compressionRateLabel = new javax.swing.JLabel();
        selectFileButton = new javax.swing.JButton();
        filePathField = new javax.swing.JTextField();
        compressionRateField = new javax.swing.JTextField();
        proccessImageButton = new javax.swing.JButton();
        originalPanel = new java.awt.Panel();
        compressedPanel = new java.awt.Panel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        compressionRateSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                compressionRateSliderStateChanged(evt);
            }
        });
        compressionRateSlider.setPaintTicks(true);
        compressionRateSlider.setPaintLabels(true);
        compressionRateSlider.setMajorTickSpacing(10);
        compressionRateSlider.setMinorTickSpacing(5);

        compressionRateLabel.setText("Taxa de Compressão");

        selectFileButton.setText("Selecione o Arquivo");
        filePathField.setText(null);
        selectFileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectFileButtonMouseClicked(evt);
            }
        });

        filePathField.setEditable(false);

        compressionRateField.setEditable(false);
        compressionRateField.setText(compressionRateSlider.getValue() + " %");

        proccessImageButton.setText("Processar Imagem");
        proccessImageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proccessImageButtonMouseClicked(evt);
            }
        });
        proccessImageButton.setEnabled(false);

        javax.swing.GroupLayout originalPanelLayout = new javax.swing.GroupLayout(originalPanel);
        originalPanel.setLayout(originalPanelLayout);
        originalPanelLayout.setHorizontalGroup(
            originalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        originalPanelLayout.setVerticalGroup(
            originalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout compressedPanelLayout = new javax.swing.GroupLayout(compressedPanel);
        compressedPanel.setLayout(compressedPanelLayout);
        compressedPanelLayout.setHorizontalGroup(
            compressedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 363, Short.MAX_VALUE)
        );
        compressedPanelLayout.setVerticalGroup(
            compressedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(filePathField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectFileButton))
            .addComponent(compressionRateSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(compressionRateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(compressionRateField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(proccessImageButton)
                .addGap(0, 41, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(originalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(compressedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectFileButton)
                    .addComponent(filePathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(compressionRateSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compressionRateLabel)
                    .addComponent(compressionRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proccessImageButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(originalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(compressedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        originalPanel.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /*
        Cria a tela para seleção da imagem
    */
    private void selectFileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectFileButtonMouseClicked

        JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new File(System.getProperty("user.dir")));
        FileFilter ff = new FileFilter() {
            
            // Define o tipo de arquivo que pode ser selecionado.
            @Override
            public boolean accept(File f) {
                return f.getName().endsWith(".ppm") || f.isDirectory();
            }

            @Override
            public String getDescription() {
                return "PPM files (*.ppm)";
            }

        };

        fc.addChoosableFileFilter(ff);
        fc.setFileFilter(ff);

        int returnValue = fc.showOpenDialog((Component) evt.getSource());

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            if (inputFile == null || !fc.getSelectedFile().getAbsolutePath().equals(inputFile.getAbsolutePath())) {
                proccessImageButton.setEnabled(true);
                changeFile = true;

                inputFile = fc.getSelectedFile();
                filePathField.setText(inputFile.getAbsolutePath());

                originalPanel.removeAll();
                originalPanel.repaint();
                compressedPanel.removeAll();
                compressedPanel.repaint();
            }

        }
    }//GEN-LAST:event_selectFileButtonMouseClicked

    private void compressionRateSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_compressionRateSliderStateChanged
        JSlider source = (JSlider) evt.getSource();
        compressionRateField.setText(source.getValue() + " %");
        if (!invalidFile) {
            proccessImageButton.setEnabled(true);
            compressedPanel.removeAll();
            compressedPanel.repaint();
        }
    }//GEN-LAST:event_compressionRateSliderStateChanged

    // Método que carrega o arquivo selecionado e o comprime conforme seleção do usuário.
    private void proccessImageButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proccessImageButtonMouseClicked

        if (!proccessImageButton.isEnabled()) {
            return;
        }
        
        proccessImageButton.setEnabled(false);
        
        //SE é a primeira vez que o arquivo está sendo inserido e comprimido
        if (changeFile) {
            
            List<String> lines = null;

            try {
                // Carrega todo o arquivo para a Lista
                lines = Files.readAllLines(Paths.get(inputFile.getAbsolutePath()));
            } catch (IOException ex) {
                Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
            }
            // Remove a primeira linha do arquivo e verifica se tipo de arquivo é do tipo P3
            if (!"P3".equals(lines.remove(0).toUpperCase())) {
                JOptionPane.showMessageDialog(this, "Tipo do arquivo incorreto.", "Dialog", JOptionPane.ERROR_MESSAGE);
                invalidFile = true;
                return;
            }

            invalidFile = false;
            // Remove a segunda linha do arquivo para pegar a altura e a largura da imagem ppm
            String[] size = lines.remove(0).split(" ");
            int width = Integer.valueOf(size[0]);
            int height = Integer.valueOf(size[1]);

            int maxrgb = Integer.valueOf(lines.remove(0));
            
            // Cria um array com tamanho da altura X tamanho largura do arquivo importado para armazenar os pixels.
            int[] pixels = new int[width * height];

            System.out.println(new SimpleDateFormat("dd/MM/yyyy hh:mm ").format(new Date()) + "Identificando RGBs");
            
            for (int i = 0; i < pixels.length; i++) {
                // Remove a proxima linha que será a cor vermelha
                int r = Integer.valueOf(lines.remove(0));
                // Remove a proxima linha que será a cor verde
                int g = Integer.valueOf(lines.remove(0));
                // Remove a proxima linha que será a cor azul
                int b = Integer.valueOf(lines.remove(0));

                //0x00FF0000 -> hexadecimal do vermelho
                //0x0000FF00 -> hexadecimal do verde
                //0x000000FF -> hexadecimal do azul                
                r = (r << 16) & 0x00FF0000; // bits (16 a 23) reservados para o valor do canal R (red)
                g = (g << 8) & 0x0000FF00;  // bits (8 a 15) reservados para o valor do canal G (green)
                b = b & 0x000000FF;         // bits (0 a 7) reservados para o valor do canal B (blue)

                pixels[i] = 0xFF000000 | r | g | b; // Junta e adiciona ao array de pixels.
            }

            System.out.println(new SimpleDateFormat("dd/MM/yyyy hh:mm ").format(new Date()) + "Imprimindo Imagem Original");
            // Imprime a imagem original.
            imagePanel = new ImagePanel(width, height);
            imagePanel.update(pixels, width, height);
            originalPanel.add(imagePanel);
            originalPanel.setSize(width, height);
            originalPanel.setMinimumSize(originalPanel.getSize());
            originalPanel.setVisible(true);
            originalPanel.repaint();

            //pack();
            // Cria a QuadTree passando o array de pixels, a largura da imagem, a altura da imagem e a taxa de compressão.
            tree = new QuadTree(pixels, width, height, compressionRateSlider.getValue());
            changeFile = false;
        } else {
            // Senão altera a taxa de compressão do arquivo conforme definição do usuário.
            tree.compressImage(compressionRateSlider.getValue());
        }
        
        System.out.println(new SimpleDateFormat("dd/MM/yyyy hh:mm ").format(new Date()) + "Imprimindo Imagem Comprimida");
        
        // Carrega a imagem que foi comprimida para ser visualizada na tela.
        int[] teste = tree.getCompressedArray();
        
        compressedImagePanel = new ImagePanel(tree.getOriginalWidth(), tree.getOriginalHeight());
        compressedImagePanel.update(teste, tree.getOriginalWidth(), tree.getOriginalHeight());
        compressedPanel.add(compressedImagePanel);
        compressedPanel.setSize(tree.getOriginalWidth(), tree.getOriginalHeight());
        compressedPanel.setMinimumSize(compressedPanel.getSize());
        compressedPanel.setVisible(true);
        compressedPanel.repaint();

        try {
            
            File directory = new File(Paths.get(System.getProperty("user.dir"), "json").toString());

            if (!directory.exists()) {
                directory.mkdir();
            }
            // Grava arquivo da arvore comprimida em um arquivo PPM
            File ppmFile = new File(Paths.get(directory.getAbsolutePath(), "compressed.ppm").toString());

            String ppm = "";
            for (int t : teste) {
                Color c = new Color(t);
                ppm += c.getRed() + System.getProperty("line.separator");
                ppm += c.getGreen() + System.getProperty("line.separator");
                ppm += c.getBlue() + System.getProperty("line.separator");
            }
            FileWriter ppmWriter = new FileWriter(ppmFile);
            ppmWriter.write(ppm);
            ppmWriter.close();

        } catch (IOException e) {
            e.printStackTrace();
        }

        pack();

    }//GEN-LAST:event_proccessImageButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel compressedPanel;
    private javax.swing.JTextField compressionRateField;
    private javax.swing.JLabel compressionRateLabel;
    private javax.swing.JSlider compressionRateSlider;
    private javax.swing.JTextField filePathField;
    private java.awt.Panel originalPanel;
    private javax.swing.JButton proccessImageButton;
    private javax.swing.JButton selectFileButton;
    // End of variables declaration//GEN-END:variables
    private File inputFile;
    private boolean invalidFile;
    private boolean changeFile;
    private ImagePanel imagePanel;
    private ImagePanel compressedImagePanel;
    private QuadTree tree;
}
