/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estruturasdados.trabalhoGB;

import br.unisinos.imagepanel.ImagePanel;
import estruturasdados.trabalhoGB.Domain.QuadTree;
import estruturasdados.trabalhoGB.Helpers.FileHelper;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author rosted
 */
public class trabalhoGB extends javax.swing.JFrame {

    /**
     * Creates new form trabalhoGB
     */
    public trabalhoGB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

      pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FileHelper fh = new FileHelper();

        File input = fh.getFile();
        List<String> lines = null;
        boolean validFile = false;

        do {
            try {
                lines = Files.readAllLines(Paths.get(input.getAbsolutePath()));
            } catch (IOException ex) {
                Logger.getLogger(trabalhoGB.class.getName()).log(Level.SEVERE, null, ex);
            }

            if ("P3".equals(lines.remove(0).toUpperCase())) {
                validFile = true;
            } else {
                System.out.println("Arquivo incorreto! Tente novamente.");
                input = fh.getFile();
            }
        } while (!validFile);

        String[] size = lines.remove(0).split(" ");
        int width = Integer.valueOf(size[0]);
        int height = Integer.valueOf(size[1]);

        int maxrgb = Integer.valueOf(lines.remove(0));

        int[] pixels = new int[width * height];

        for (int i = 0; i < pixels.length; i++) {
            int r = Integer.valueOf(lines.remove(0));
            int g = Integer.valueOf(lines.remove(0));
            int b = Integer.valueOf(lines.remove(0));

            //0x00FF0000 -> hexadecimal do vermelho
            //0x0000FF00 -> hexadecimal do verde
            //0x000000FF -> hexadecimal do azul
            r = (r << 16) & 0x00FF0000;
            g = (g << 8) & 0x0000FF00;
            b = b & 0x000000FF;

            pixels[i] = 0xFF000000 | r | g | b;
        }

        trabalhoGB.imagePanel = new ImagePanel();
        trabalhoGB.imagePanel.update(pixels, width, height);

        QuadTree tree = new QuadTree(pixels, width, height);

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(trabalhoGB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(trabalhoGB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(trabalhoGB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(trabalhoGB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new trabalhoGB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                       
    private static ImagePanel imagePanel;
    // End of variables declaration                   
}
